project_id = "cplyzukenqxdwhfivlqx"

[functions.email-send]
verify_jwt = false

[functions.birch-ai]
verify_jwt = false

[functions.birch-probe]
verify_jwt = false

[functions.admin-api]
verify_jwt = false
